Insert into Examiner(ID,name,email,experienceYears,specialization,status)
 values 
           ('EX248','Nguyễn Thế Hoàng','hoangntex248@fe.edu.vn',7,'Infomation Technology',1);
		   ('EX165','Lâm Hữu Khánh Phương','phuonglhkex165@fe.edu.vn',15,'Infomation Technology',1);
		   ('EX392','Trần Ngọc Châu','chautnex392@fe.edu.vn',13,'Infomation Technology',1);
		   ('EX412','Tăng Quang Hiếu','hieutqex412@fe.edu.vn',5,'Infomation Technology',1);
		   ('EX752','Vũ Thị Thùy Dưong','duongvttex752@fe.edu.vn',10,'Infomation Technology',1);
		  ('EX454','Thân Thị Ngọc Vân','vanttnex454@fe.edu.vn',10,'Infomation Technology',1);
                  ('EX123','Trần Công Đời','Doictex123@fe.edu.vn',7,'Infomation Technology',1);
		   ('EX124','Đỗ Tấn Nhàn','Nhandtex124@fe.edu.vn',10,'Infomation Technology',1);
		   ('EX489','Thân Văn Sử','Sutvex489@fe.edu.vn',15,'Infomation Technology',1);
		   ('EX125','Nguyễn Minh Sang','Sangntex125@fe.edu.vn',9,'Infomation Technology',1);
		  ('EX126','Hồ Hoàn Kiếm','Kiemhhex126@fe.edu.vn',7,'Infomation Technology',1);
         --     ('EX127','Tô Thị Thùy Dương','duongex127@fe.edu.vn',5,'Digital Art & Design',1);
		 --  ('EX128','Vũ Tùng Linh','linhvt128@fe.edu.vn',4,'Digital Art & Design',1);
		--  ('EX129','Lưu Nhật Lan','lannmex129@fe.edu.vn',5,'Digital Art & Design',1);
		 --  ('EX130','Nguyễn Thị Thanh Nhàn','nhannttex130@fe.edu.vn',5,'Digital Art & Design',1);
		--   ('EX131','Nguyễn Hữu Hoàng Giao','giaonhnex131@fe.edu.vn',5,'Digital Art & Design',1);
		--   ('EX132','Trần Duy Khiêm,','khiemtdex132@fe.edu.vn',5,'Digital Art & Design',1);
		  -- ('EX133','La Thị Cẩm Tú','tultcẽ133@fe.edu.vn',5,'Digital Art & Design',1);
		--   ('EX134','Phó Thị Mỹ Hạnh','hanhptmex134@fe.edu.vn',5,'Digital Art & Design',1);
		 --  ('EX135','Nguyễn Mai Lan','lannmex135@fe.edu.vn',5,'Digital Art & Design',1);
		   ('EX136','Lê Phát Minh','minhlpex136@fe.edu.vn',7,'Digital Art & Design',1);
               ('EX137','Võ Thị Vân Na','navtvex137@fe.edu.vn',5,'Finance',1);
	--  ('EX138','Nguyễn Hoàng Yến Như','nhunhyex138@fe.edu.vn',7,'Finance',1);
	--  ('EX139','Dư Tiểu Dương','duongdtex139@fe.edu.vn',5,'Finance',1);
	--  ('EX140','Lâm Thị Hoàng Diễm','diemlthex140@fe.edu.vn',6,'Finance',1);
	--  ('EX141','Nguyễn Thị Thới','thointex141@fe.edu.vn',4,'Finance',1);
	 -- ('EX142','Nguyễn Quốc Bảo','baonqex142@fe.edu.vn',5,'Finance',1);
	--  ('EX143',N'Nguyễn Chính Quang','quangncex143@fe.edu.vn',3,'Finance',1);
	  ('EX144','Trần Đình Thành','thanhex144@fe.edu.vn',4,'Finance',1);
 --   ('EX145','Nguyễn Ba Lê','Lenbex145@fe.edu.vn',5,'International Business',1);
		 --   ('EX146','Trương Thị Thúy Vân','vantttex146@fe.edu.vn',5,'International Business',1);
		--	 ('EX147','Trần Khánh','khanhtex147@fe.edu.vn',5,'International Business',1);
		--  ('EX148',N'Phan Hoàng Hà','haph148@fe.edu.vn',5,'International Business',1);
