Insert into Examiner(ID,name,email,experienceYears,specialization,status)
 values 
           ('EX248',N'Nguyễn Thế Hoàng','hoangntex248@fe.edu.vn',7,'Infomation Technology',1);
		   ('EX165',N'Lâm Hữu Khánh Phương','phuonglhkex165@fe.edu.vn',15,'Infomation Technology',1);
		   ('EX392',N'Trần Ngọc Châu','chautnex392@fe.edu.vn',13,'Infomation Technology',1);
		   ('EX412',N'Tăng Quang Hiếu','hieutqex412@fe.edu.vn',5,'Infomation Technology',1);
		   ('EX752',N'Vũ Thị Thùy Dưong','duongvttex752@fe.edu.vn',10,'Infomation Technology',1);
		   ('EX454',N'Thân Thị Ngọc Vân','vanttnex454@fe.edu.vn',10,'Infomation Technology',1);
                   ('EX123',N'Trần Công Đời','Doictex123@fe.edu.vn',7,'Infomation Technology',1);
		   ('EX124',N'Đỗ Tấn Nhàn','Nhandtex124@fe.edu.vn',10,'Infomation Technology',1);
		   ('EX489',N'Thân Văn Sử','Sutvex489@fe.edu.vn',15,'Infomation Technology',1);
		   ('EX125',N'Nguyễn Minh Sang','Sangntex125@fe.edu.vn',9,'Infomation Technology',1);
		   ('EX126',N'Hồ Hoàn Kiếm','Kiemhhex126@fe.edu.vn',7,'Infomation Technology',1);
                   ('EX127',N'Tô Thị Thùy Dương','duongex127@fe.edu.vn',5,'Digital Art & Design',1);
		   ('EX128',N'Vũ Tùng Linh','linhvt128@fe.edu.vn',4,'Digital Art & Design',1);
		   ('EX129',N'Lưu Nhật Lan','lannmex129@fe.edu.vn',5,'Digital Art & Design',1);
		   ('EX130',N'Nguyễn Thị Thanh Nhàn','nhannttex130@fe.edu.vn',5,'Digital Art & Design',1);
		   ('EX131',N'Nguyễn Hữu Hoàng Giao','giaonhnex131@fe.edu.vn',5,'Digital Art & Design',1);
		   ('EX132',N'Trần Duy Khiêm,','khiemtdex132@fe.edu.vn',5,'Digital Art & Design',1);
		   ('EX133',N'La Thị Cẩm Tú','tultcẽ133@fe.edu.vn',5,'Digital Art & Design',1);
		   ('EX134',N'Phó Thị Mỹ Hạnh','hanhptmex134@fe.edu.vn',5,'Digital Art & Design',1);
		   ('EX135',N'Nguyễn Mai Lan','lannmex135@fe.edu.vn',5,'Digital Art & Design',1);
		   ('EX136',N'Lê Phát Minh','minhlpex136@fe.edu.vn',7,'Digital Art & Design',1);
                   ('EX137',N'Võ Thị Vân Na','navtvex137@fe.edu.vn',5,'Finance',1);
	           ('EX138',N'Nguyễn Hoàng Yến Như','nhunhyex138@fe.edu.vn',7,'Finance',1);
	           ('EX139',N'Dư Tiểu Dương','duongdtex139@fe.edu.vn',5,'Finance',1);
	           ('EX140',N'Lâm Thị Hoàng Diễm','diemlthex140@fe.edu.vn',6,'Finance',1);
	           ('EX141',N'Nguyễn Thị Thới','thointex141@fe.edu.vn',4,'Finance',1);
	           ('EX142',N'Nguyễn Quốc Bảo','baonqex142@fe.edu.vn',5,'Finance',1);
	           ('EX143',N'Nguyễn Chính Quang','quangncex143@fe.edu.vn',3,'Finance',1);
	           ('EX144',N'Trần Đình Thành','thanhex144@fe.edu.vn',4,'Finance',1);
                   ('EX145',N'Nguyễn Ba Lê','Lenbex145@fe.edu.vn',5,'International Business',1);
		   ('EX146',N'Trương Thị Thúy Vân','vantttex146@fe.edu.vn',5,'International Business',1);
	           ('EX147',N'Trần Khánh','khanhtex147@fe.edu.vn',5,'International Business',1);
		   ('EX148',N'Phan Hoàng Hà','haph148@fe.edu.vn',5,'International Business',1);
                   ('EX150',N'Huỳnh Tấn Hội','hoihtex150@fe.edu.vn',5,'Japanese ',1);
		   ('EX151',N'Trần Thị Duyên Phượng','phuongttdex151@fe.edu.vn',4,'Japanese ',1);
		   ('EX152',N'Trần Anh Kiều','kieutaex152@fe.edu.vn',5,'Japanese ',1);
		   ('EX153',N'Đình Lan Hương','huongdlex153@fe.edu.vn',3,'Japanese ',1);
		   ('EX154',N'Đỗ Thị Hồng Cẩm','camdthex154@fe.edu.vn',5,'Japanese ',1);
           	   ('EX155',N'Đặng Công Đoàn','doandcex155@fe.edu.vn',5,'Japanese ',1);
                   ('EX156',N' Nguyễn Hải Anh','anhnhex156@fe.edu.vn',5,'Marketing',1);
		   ('EX157',N'Mai Anh Duy','duymaex157@fe.edu.vn',5,'Marketing',1);
		   ('EX158',N' Hồ Yên Thục','thuchyex158@fe.edu.vn',8,'Marketing',1);
		   ('EX159',N' Nguyễn Huyền Trang','trangnthex159@fe.edu.vn',5,'Marketing',1);
		   ('EX160',N' Hồ Trung Chánh','chanhhtex160@fe.edu.vn',5,'Marketing',1);
		   ('EX161',N'Trần Cẩm Bình','binhtcex161@fe.edu.vn',5,'Marketing',1);
                   ('EX166',N'Kiều Minh Quyền','quyenkmex166@fe.edu.vn',5,'English',1);
		   ('EX167',N'Nguyễn Thị Diệu Hiền','hienntdex167@fe.edu.vn',8,'English',1);
		   ('EX168',N'Phan Thùy Thiên Hương','huongpthtex168@fe.edu.vn',5,'English',1);
		   ('EX169',N'Nguyễn Long Quốc','quocnlex169@fe.edu.vn',7,'English',1);
		   ('EX170',N' Karen Cheermaine Badong','karencbex170@fe.edu.vn',7,'English',1);
